import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { SimulatedOrderForm } from "../components/SimulatedOrderForm";
import { useRecommendationDetail } from "../hooks/useRecommendationDetail";

export function RecommendationDetail() {
  const { id } = useParams<{ id: string }>();
  const [refreshKey, setRefreshKey] = useState(0);
  const { data: recommendation, loading, error } = useRecommendationDetail(id ?? "", refreshKey);

  if (loading) return <p>Loading recommendation...</p>;
  if (error) return <p className="error">Failed to load recommendation: {error.message}</p>;
  if (!recommendation) return <p>Recommendation not found.</p>;

  const { scoring_breakdown: breakdown } = recommendation;

  return (
    <div className={`recommendation-detail direction-${recommendation.direction}`}>
      <Link to="/" className="back-link">
        &larr; Back to recommendations
      </Link>

      <header>
        <h2>{recommendation.ticker}</h2>
        <span className={`badge conviction-${recommendation.conviction}`}>
          {recommendation.direction.toUpperCase()} &middot; {recommendation.conviction} conviction
        </span>
      </header>

      <p className="signal-score">Signal score: {recommendation.signal_score.toFixed(4)}</p>
      <p className="model-version">Generated by {recommendation.model_version}</p>

      {recommendation.rationale_text && (
        <section>
          <h3>Rationale</h3>
          <p className="rationale">{recommendation.rationale_text}</p>
        </section>
      )}

      <section>
        <h3>Scoring breakdown</h3>
        <ul className="breakdown-summary">
          <li>Raw signal total: {breakdown.raw_total.toFixed(4)}</li>
          <li>
            Agreeing politicians: {breakdown.agreeing_politicians} of {breakdown.total_politicians}
          </li>
          <li>Consensus multiplier: {breakdown.consensus_multiplier.toFixed(3)}x</li>
        </ul>

        {recommendation.supporting_trades.length > 0 && (
          <table className="trade-table">
            <thead>
              <tr>
                <th>Politician</th>
                <th>Direction</th>
                <th>Date</th>
                <th>Amount (mid)</th>
                <th>Recency wt.</th>
                <th>Size wt.</th>
                <th>Contribution</th>
              </tr>
            </thead>
            <tbody>
              {recommendation.supporting_trades.map((trade) => (
                <tr key={trade.canonical_trade_id}>
                  <td>{trade.politician_name}</td>
                  <td className={`transaction-${trade.transaction_type}`}>
                    {trade.transaction_type}
                  </td>
                  <td>{trade.transaction_date}</td>
                  <td>${trade.amount_mid.toLocaleString()}</td>
                  <td>{trade.recency_weight.toFixed(3)}</td>
                  <td>{trade.size_weight.toFixed(3)}</td>
                  <td>{trade.signal_contribution.toFixed(4)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>

      <section>
        <h3>Simulate a trade</h3>
        <SimulatedOrderForm
          recommendationId={recommendation.id}
          direction={recommendation.direction}
          onOrderPlaced={() => setRefreshKey((key) => key + 1)}
        />

        {recommendation.simulated_orders.length > 0 && (
          <>
            <h4>Order history</h4>
            <table className="trade-table">
              <thead>
                <tr>
                  <th>Side</th>
                  <th>Quantity</th>
                  <th>Price</th>
                  <th>Notional value</th>
                  <th>Logged at</th>
                </tr>
              </thead>
              <tbody>
                {recommendation.simulated_orders.map((order) => (
                  <tr key={order.id}>
                    <td className={`transaction-${order.side}`}>{order.side}</td>
                    <td>{order.quantity}</td>
                    <td>${order.price.toLocaleString()}</td>
                    <td>${order.notional_value.toLocaleString()}</td>
                    <td>{new Date(order.created_at).toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </>
        )}
      </section>
    </div>
  );
}
